name: AWS Based Kubernetes Deployment Workflow

on:
  workflow_call:
    inputs:
      deploy-branches:
        required: true
        type: string
      k8s-deployment-name:
        required: true
        type: string
      push-branches:
        required: true
        type: string
    secrets:
      AWS_SECURITY_GROUP_MODIFIER_ACCESS_KEY_ID:
        required: true
      AWS_SECURITY_GROUP_MODIFIER_SECRET_KEY:
        required: true
      AWS_SECURITY_GROUP_REGION:
        required: true
      AWS_SECURITY_GROUP_NAME:
        required: true

jobs:
  build-push-images:
    uses: elementalcodeworks/github-actions-workflows/.github/workflows/build-push-workflow.yaml@1.x
    with:
      push-branches: ${{ inputs.push-branches }}

  add-runner-to-aws-security-group:
    if: contains(fromJSON(inputs.deploy-branches), github.ref)
    name: Add Runner IP to Security Group
    runs-on: ubuntu-latest
    needs: [build-push-images]
    steps:
      -
        name: Get Github Action Runner IP
        id: ip
        uses: haythem/public-ip@v1.2
      -
        name: Add Github Actions IP for kubectl to Security Group
        run: |
          aws ec2 authorize-security-group-ingress --group-name ${{ env.AWS_SECURITY_GROUP_NAME }} --protocol tcp --port 6443 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECURITY_GROUP_MODIFIER_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_SECURITY_GROUP_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECURITY_GROUP_MODIFIER_SECRET_KEY }}
          AWS_SECURITY_GROUP_NAME: ${{ secrets.AWS_SECURITY_GROUP_NAME }}

  deploy-built-image-to-kubernetes:
    name: Deploy Built Image to Kubernetes
    runs-on: ubuntu-latest
    needs: [add-runner-to-aws-security-group]
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      -
        name: Retrieve Image Tag
        uses: actions/download-artifact@v3
        with:
          name: build-image-tag
          path: /tmp
      -
        name: Set Image Tag
        run: cat /tmp/image_tag.env >> $GITHUB_ENV
      -
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          DEPLOYMENT_IMAGE: ${{ env.BUILD_IMAGE_FULL_NAME }}
          DEPLOYMENT_NAME: ${{ inputs.k8s-deployment-name }}
        with:
          args: set image "deployment/$DEPLOYMENT_NAME" "$DEPLOYMENT_IMAGE" --namespace="$CI_REF_NAME"

  remove-runner-from-aws-security-group:
    if: always()
    name: Remove Runner IP from Security Group
    runs-on: ubuntu-latest
    needs: [deploy-built-image-to-kubernetes, add-runner-to-aws-security-group]
    steps:
      -
        name: Get Github Action Runner IP
        id: ip
        uses: haythem/public-ip@v1.2
      -
        name: Remove Github Actions IP from security group
        run: |
          aws ec2 revoke-security-group-ingress --group-name ${{ env.AWS_SECURITY_GROUP_NAME }} --protocol tcp --port 6443 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECURITY_GROUP_MODIFIER_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_SECURITY_GROUP_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECURITY_GROUP_MODIFIER_SECRET_KEY }}
          AWS_SECURITY_GROUP_NAME: ${{ secrets.AWS_SECURITY_GROUP_NAME }}
