name: AWS Based Kubernetes Deployment Workflow

on:
  workflow_call:
    inputs:
      branch-env-map:
          required: true
          type: string
      deploy-branches:
        required: true
        type: string
      k8s-deployment-name:
        required: true
        type: string
      push-branches:
        required: true
        type: string
    secrets:
      AWS_SECURITY_GROUP_MODIFIER_ACCESS_KEY_ID:
        required: true
      AWS_SECURITY_GROUP_MODIFIER_SECRET_KEY:
        required: true
      AWS_SECURITY_GROUP_REGION:
        required: true
      AWS_SECURITY_GROUP_NAME:
        required: true
      KUBE_CONFIG:
        required: true

jobs:
  build-push-images:
    uses: elementalcodeworks/github-actions-workflows/.github/workflows/build-push-workflow.yaml@1.x
    with:
      push-branches: ${{ inputs.push-branches }}

  deploy-image-to-k8s:
    if:
      ${{ contains(fromJSON(${{ inputs.deploy-branches }}), github.ref_name) }}
    name: Deploy New Image to Kubernetes Cluster
    runs-on: ubuntu-latest
    needs: [build-push-images]
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      -
        name: Retrieve Built Image Tag
        uses: actions/download-artifact@v3
        with:
          name: build-image-tag
          path: /tmp
      -
        name: Set Built Image Tag Locally
        run: cat /tmp/image_tag.env >> $GITHUB_ENV
      -
        name: Get Github Action Runner IP
        id: ip
        uses: haythem/public-ip@v1.2
      -
        name: Add Github Actions IP for kubectl to AWS Security Group
        uses: sohelamin/aws-security-group-add-ip-action@master
        with:
          aws-access-key-id: ${{ secrets.AWS_SECURITY_GROUP_MODIFIER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECURITY_GROUP_MODIFIER_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_SECURITY_GROUP_REGION }}
          aws-security-group-id: ${{ secrets.AWS_SECURITY_GROUP_NAME }}
          port: '6443'
          to-port: '6443'
          protocol: 'tcp'
          description: 'GitHub Actions Runner kubectl Access'
      -
        name: Write Deployment Namespaces To Local
        run: echo '${{ inputs.branch-env-map }}' > /tmp/deployment_namespaces.json
      -
        name: Set Deployment Namespace
        run: echo "DEPLOYMENT_NAMESPACE=$(jq -r '.${{ github.ref_name }}' /tmp/deployment_namespaces.json)" >> $GITHUB_ENV
      - uses: azure/setup-kubectl@v3
        name: Install Kubectl
        with:
          version: 'v1.26.2'
        id: install-kubectl
      - uses: azure/k8s-set-context@v3
        name: Set Kubectl Context
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
        id: setcontext-kubectl
      -
        name: Update Image In Kubernetes Deployment
        run: |
          kubectl set image "deployment/$DEPLOYMENT_NAME" "$DEPLOYMENT_NAME=$DEPLOYMENT_IMAGE" --namespace="$DEPLOYMENT_NAMESPACE"
        env:
          DEPLOYMENT_IMAGE: ${{ env.BUILD_IMAGE_FULL_NAME }}
          DEPLOYMENT_NAME: ${{ inputs.k8s-deployment-name }}
          DEPLOYMENT_NAMESPACE: ${{ env.DEPLOYMENT_NAMESPACE }}
      -
        name: Wait For Deployment To Finish
        run: |
          kubectl rollout status deployment "$DEPLOYMENT_NAME" --namespace="$DEPLOYMENT_NAMESPACE"
        env:
          DEPLOYMENT_NAME: ${{ inputs.k8s-deployment-name }}
          DEPLOYMENT_NAMESPACE: ${{ env.DEPLOYMENT_NAMESPACE }}
